from __future__ import annotations


def control_page_html() -> str:
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MetaTrader AI Bridge Control</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{font-family:system-ui,sans-serif;background:#111827;color:#e5e7eb;margin:0;padding:24px}.wrap{max-width:1160px;margin:auto}.card{background:#1f2937;border:1px solid #374151;border-radius:16px;padding:20px;margin:14px 0}.row{display:grid;grid-template-columns:220px 1fr 80px;gap:14px;align-items:center;margin:14px 0}.fields{display:grid;grid-template-columns:repeat(3,minmax(140px,1fr));gap:12px}.field label{display:block;color:#9ca3af;font-size:13px;margin-bottom:6px}.field input{width:100%;background:#111827;color:white;border:1px solid #4b5563;border-radius:8px;padding:9px}.nav a{color:#bfdbfe;text-decoration:none;border:1px solid #374151;border-radius:10px;padding:9px 12px;display:inline-block}button{background:#2563eb;color:white;border:0;border-radius:10px;padding:11px 18px;font-weight:700;cursor:pointer}button.recommended{background:#0f766e}button:disabled{opacity:.5}.ok{color:#4ade80}.bad{color:#fb7185}.warn{color:#fbbf24}.muted{color:#9ca3af}code{color:#93c5fd}.metrics{display:grid;grid-template-columns:repeat(5,minmax(120px,1fr));gap:10px;margin-top:16px}.metric{background:#111827;border:1px solid #374151;border-radius:12px;padding:12px}.metric b{display:block;font-size:22px;margin-top:4px}.tablewrap{overflow:auto;margin-top:14px}table{width:100%;border-collapse:collapse;min-width:900px}th,td{padding:9px;border-bottom:1px solid #374151;text-align:left;font-size:13px}th{color:#9ca3af}@media(max-width:900px){.fields,.metrics{grid-template-columns:1fr 1fr}}@media(max-width:700px){body{padding:12px}.row{grid-template-columns:1fr}.fields,.metrics{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<h1>MetaTrader AI v2 — Bridge Control</h1><p class="muted">Live explainable thresholds, execution cap and historical replay.</p><div class="nav"><a href="/train">Open Training Lab →</a></div>
<div class="card" id="factors"></div>
<div class="card"><h2>Decision & execution gates</h2><div class="row"><label>Minimum passed factors</label><input id="min_pass_count" type="range" min="1" max="6"><input id="min_pass_count_n" type="number" min="1" max="6"></div><div class="row"><label>Minimum total score</label><input id="min_total_score" type="range" min="0" max="100"><input id="min_total_score_n" type="number" min="0" max="100"></div><div class="row"><label>Minimum BUY/SELL edge</label><input id="min_side_edge" type="range" min="0" max="100"><input id="min_side_edge_n" type="number" min="0" max="100"></div><div class="row"><label>Max concurrent trades</label><input id="max_open_trades" type="range" min="1" max="5" step="1"><input id="max_open_trades_n" type="number" min="1" max="5" step="1"></div><p class="muted">Live effective limit = min(Bridge value, EA local <code>MaxOpenTrades</code>). Set the EA local ceiling to 5 once if you want Bridge control from 1–5.</p></div>
<p><button id="saveBtn">Save live settings</button> <span id="status"></span></p>
<div class="card"><h2>Model-recommended profile</h2><p id="recommendInfo" class="muted">Checking recommendation…</p><p><button id="recommendBtn" class="recommended">Apply model-recommended settings</button> <span id="recommendStatus"></span></p><p class="muted">Recommended profile changes analysis thresholds only. Execution settings such as max concurrent trades are preserved.</p></div>
<div class="card"><h2>Historical range replay</h2><p id="historyStatus" class="muted">Checking MT5 history…</p><div class="fields"><div class="field"><label>Start date</label><input id="btStartDate" type="date"></div><div class="field"><label>End date</label><input id="btEndDate" type="date"></div><div class="field"><label>Starting balance $</label><input id="btBalance" type="number" min="10" value="1000"></div><div class="field"><label>Risk / trade %</label><input id="btRisk" type="number" min="0.01" max="5" step="0.05" value="0.5"></div><div class="field"><label>Reward : Risk</label><input id="btRR" type="number" min="0.5" max="10" step="0.1" value="2"></div><div class="field"><label>Max concurrent trades</label><input id="btMaxOpen" type="number" min="1" max="5" step="1" value="1"></div></div><p><button id="runBt" disabled>Run selected range</button> <span id="btMsg" class="muted"></span></p><div id="btResult"></div></div>
</div><script>
const factors=['dynamic_levels','static_levels','fibonacci','patterns','pivots','divergence'];let cfg,dates=[];const $=id=>document.getElementById(id);function bind(id,value){$(id).value=value;$(id+'_n').value=value;$(id).oninput=()=>$(id+'_n').value=$(id).value;$(id+'_n').oninput=()=>$(id).value=$(id+'_n').value}function money(v){const n=Number(v)||0;return `${n<0?'-$':'$'}${Math.abs(n).toFixed(2)}`}
async function load(){cfg=await(await fetch('/strategy/config')).json();$('factors').innerHTML='<h2>Factor minimums</h2>'+factors.map(n=>`<div class="row"><label>${n.replaceAll('_',' ')}</label><input id="${n}" type="range" min="0" max="100"><input id="${n}_n" type="number" min="0" max="100"></div>`).join('');for(const n of factors)bind(n,cfg[n].min_score);bind('min_pass_count',cfg.decision.min_pass_count);bind('min_total_score',cfg.decision.min_total_score);bind('min_side_edge',cfg.decision.min_side_edge);bind('max_open_trades',cfg.safety.max_open_trades||1);$('btMaxOpen').value=cfg.safety.max_open_trades||1;await Promise.all([history(),recommend()])}
async function save(){for(const n of factors)cfg[n].min_score=Number($(n).value);cfg.decision.min_pass_count=Number($('min_pass_count').value);cfg.decision.min_total_score=Number($('min_total_score').value);cfg.decision.min_side_edge=Number($('min_side_edge').value);cfg.safety.max_open_trades=Number($('max_open_trades').value);const r=await fetch('/strategy/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});$('status').textContent=r.ok?'Saved':'Save failed';$('status').className=r.ok?'ok':'bad';if(r.ok){cfg=await r.json();$('btMaxOpen').value=cfg.safety.max_open_trades}}
async function recommend(){try{const d=await(await fetch('/strategy/recommended')).json();$('recommendInfo').textContent=`Source: ${d.source} · ${d.sample_size} forward trades. ${d.reasons.join(' ')}`}catch(e){$('recommendInfo').textContent=e.message}}
async function applyRec(){const r=await fetch('/strategy/apply-recommended',{method:'POST'}),d=await r.json();if(!r.ok){$('recommendStatus').textContent=d.detail||'Failed';$('recommendStatus').className='bad';return}cfg=d;for(const n of factors){$(n).value=d[n].min_score;$(n+'_n').value=d[n].min_score}for(const n of ['min_pass_count','min_total_score','min_side_edge']){$(n).value=d.decision[n];$(n+'_n').value=d.decision[n]}$('max_open_trades').value=d.safety.max_open_trades;$('max_open_trades_n').value=d.safety.max_open_trades;$('recommendStatus').textContent='Applied; execution cap preserved';$('recommendStatus').className='ok'}
async function history(){try{const h=await(await fetch('/history/status?symbol=XAUUSD_o&timeframe=M15')).json();if(!h.bars)throw new Error('No history synced yet');dates=(h.available_dates||[]).slice().sort();$('historyStatus').textContent=`Synced ${h.bars} bars · ${h.earliest_date} → ${h.latest_date}`;$('historyStatus').className='ok';for(const id of ['btStartDate','btEndDate']){$(id).min=h.earliest_date;$(id).max=h.latest_date}$('btEndDate').value=dates[dates.length-1];$('btStartDate').value=dates[Math.max(0,dates.length-20)];$('runBt').disabled=false}catch(e){$('historyStatus').textContent=e.message;$('historyStatus').className='warn'}}
function metric(label,value,sub=''){return `<div class="metric"><span class="muted">${label}</span><b>${value}</b><small>${sub}</small></div>`}function time(x){return new Date(x*1000).toISOString().replace('T',' ').slice(0,16)}
async function replay(){const start=$('btStartDate').value,end=$('btEndDate').value,maxOpen=Number($('btMaxOpen').value),balance0=Number($('btBalance').value),risk=Number($('btRisk').value),rr=Number($('btRR').value);if(!start||!end||start>end||maxOpen<1||maxOpen>5){$('btMsg').textContent='Check dates and concurrent limit 1–5';$('btMsg').className='bad';return}const selected=dates.filter(d=>d>=start&&d<=end);let balance=balance0;const days=[];$('runBt').disabled=true;try{for(let i=0;i<selected.length;i++){$('btMsg').textContent=`Replaying ${i+1}/${selected.length}…`;const q=new URLSearchParams({date:selected[i],symbol:'XAUUSD_o',timeframe:'M15',starting_balance:String(balance),risk_percent:String(risk),reward_risk_ratio:String(rr),max_open_trades:String(maxOpen)});const r=await fetch('/backtest?'+q),d=await r.json();if(!r.ok)throw new Error(d.detail||'Backtest failed');days.push(d);balance=d.ending_balance}const trades=days.flatMap(d=>d.trades_detail.map(t=>({...t,date:d.date}))),wins=days.reduce((s,d)=>s+d.wins,0),losses=days.reduce((s,d)=>s+d.losses,0),netR=days.reduce((s,d)=>s+d.net_r,0),count=trades.length,pnl=balance-balance0,avg=days.length?pnl/days.length:0,wr=count?wins/count*100:0;let c=0,p=0,dd=0;for(const t of [...trades].sort((a,b)=>a.exit_time-b.exit_time)){c+=t.r_multiple;p=Math.max(p,c);dd=Math.max(dd,p-c)}$('btMsg').textContent=`Done · ${days.length} trading days · max ${maxOpen} concurrent`;$('btMsg').className='ok';$('btResult').innerHTML=`<div class="metrics">${metric('Trading days',days.length,'')}${metric('Trades',count,`${wins}W / ${losses}L`)}${metric('Win rate',wr.toFixed(1)+'%','')}${metric('Net R',netR.toFixed(2)+'R',`DD ${dd.toFixed(2)}R`)}${metric('Total P/L',money(pnl),`avg/day ${money(avg)}`)}</div><h3>Trades</h3><div class="tablewrap"><table><thead><tr><th>#</th><th>Date</th><th>Side</th><th>Entry</th><th>Exit</th><th>R</th><th>P/L</th><th>Passed</th></tr></thead><tbody>${trades.map((t,i)=>`<tr><td>${i+1}</td><td>${t.date}</td><td>${t.side}</td><td>${time(t.entry_time)}</td><td>${t.outcome}</td><td>${t.r_multiple.toFixed(2)}R</td><td class="${t.pnl_money>=0?'ok':'bad'}">${money(t.pnl_money)}</td><td>${t.passed_count}/6</td></tr>`).join('')||'<tr><td colspan="8">No trades.</td></tr>'}</tbody></table></div>`}catch(e){$('btMsg').textContent=e.message;$('btMsg').className='bad'}finally{$('runBt').disabled=false}}
$('saveBtn').onclick=save;$('recommendBtn').onclick=applyRec;$('runBt').onclick=replay;load();
</script></body></html>'''
