from __future__ import annotations


def training_page_html() -> str:
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MetaTrader AI Training Lab</title>
<style>
:root{color-scheme:dark;--bg:#111827;--card:#1f2937;--card2:#0f172a;--border:#374151;--text:#e5e7eb;--muted:#94a3b8;--blue:#2563eb;--green:#10b981;--amber:#f59e0b;--red:#fb7185}
*{box-sizing:border-box}body{font-family:system-ui,sans-serif;background:var(--bg);color:var(--text);margin:0;padding:24px}.wrap{max-width:1180px;margin:auto}.top{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.nav a{color:#bfdbfe;text-decoration:none;border:1px solid var(--border);border-radius:10px;padding:9px 12px;display:inline-block}.card{background:var(--card);border:1px solid var(--border);border-radius:16px;padding:20px;margin:16px 0}.muted{color:var(--muted)}.ok{color:#4ade80}.warn{color:#fbbf24}.bad{color:var(--red)}.formgrid{display:grid;grid-template-columns:repeat(3,minmax(160px,1fr));gap:12px}.field label{display:block;color:var(--muted);font-size:13px;margin-bottom:6px}.field input,.field select{width:100%;background:var(--card2);color:white;border:1px solid #475569;border-radius:9px;padding:10px;min-height:42px}.pipeline{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:10px;align-items:center}.stage{background:var(--card2);border:1px solid var(--border);border-radius:12px;padding:14px}.stage b{display:block;font-size:18px}.arrow{font-size:24px;color:#64748b}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:16px}button{background:var(--blue);color:white;border:0;border-radius:10px;padding:11px 17px;font-weight:750;cursor:pointer}button.promote{background:#0f766e}button:disabled{opacity:.45;cursor:not-allowed}.banner{border-radius:12px;padding:14px 16px;border:1px solid var(--border);background:var(--card2)}.banner.good{border-color:#166534}.banner.caution{border-color:#92400e}.metrics{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:10px;margin-top:12px}.metric{background:var(--card2);border:1px solid var(--border);border-radius:12px;padding:12px}.metric span{color:var(--muted);font-size:12px}.metric b{display:block;font-size:21px;margin:4px 0}.splitgrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:8px}.comparison div{background:#111827;border-radius:8px;padding:8px}.comparison small{color:var(--muted);display:block}.tablewrap{overflow:auto}table{border-collapse:collapse;width:100%;min-width:760px}th,td{padding:9px;border-bottom:1px solid var(--border);text-align:left;font-size:13px}th{color:var(--muted)}code{color:#93c5fd}.hidden{display:none}.progress{height:8px;background:#0f172a;border-radius:99px;overflow:hidden;margin:12px 0}.progress i{display:block;width:0;height:100%;background:#3b82f6;transition:width .4s}.note{font-size:13px;color:var(--muted);line-height:1.5}@media(max-width:900px){.formgrid,.metrics{grid-template-columns:1fr 1fr}.splitgrid,.pipeline{grid-template-columns:1fr}.arrow{transform:rotate(90deg);text-align:center}}@media(max-width:560px){body{padding:12px}.formgrid,.metrics,.comparison{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<div class="top"><div><h1>MetaTrader AI — Training Lab</h1><div class="muted">Walk-forward threshold training for XAUUSD M15. Stable rollback reference: <code>57f4e157314611dd555eb8664caa78847d43d7d3</code></div></div><div class="nav"><a href="/control">← Bridge Control</a></div></div>
<div class="card"><h2>1. Training dataset</h2><p id="historyStatus" class="muted">Reading synced MT5 history…</p><div class="formgrid">
<div class="field"><label>Start date</label><input id="startDate" type="date"></div><div class="field"><label>End date</label><input id="endDate" type="date"></div><div class="field"><label>Starting profile</label><select id="baseProfile"><option value="MODEL_BASELINE">Stable calibrated baseline</option><option value="CURRENT">Current live sliders</option></select></div>
<div class="field"><label>Candidate profiles</label><input id="iterations" type="number" min="8" max="80" value="24"></div><div class="field"><label>Starting balance $</label><input id="balance" type="number" min="10" step="10" value="1000"></div><div class="field"><label>Risk / trade %</label><input id="risk" type="number" min="0.05" max="5" step="0.05" value="0.5"></div>
<div class="field"><label>Reward : Risk</label><input id="rr" type="number" min="0.5" max="10" step="0.1" value="2"></div><div class="field"><label>Max concurrent trades</label><input id="maxOpen" type="number" min="1" max="5" step="1" value="1"></div><div class="field"><label>Tracking target $ / day</label><input id="target" type="number" min="0" step="1" value="10"></div>
</div><p class="note">Risk, R:R and max concurrent trades are held fixed during optimization. The trainer changes signal thresholds only. To reproduce the same concurrency live, the EA local <code>MaxOpenTrades</code> ceiling must be at least this value.</p></div>
<div class="card"><h2>2. Walk-forward training process</h2><div class="pipeline"><div class="stage"><b>TRAIN · 60%</b><span class="muted">Search thresholds on oldest data.</span></div><div class="arrow">→</div><div class="stage"><b>VALIDATE · 20%</b><span class="muted">Choose among the strongest candidates.</span></div><div class="arrow">→</div><div class="stage"><b>HOLDOUT · 20%</b><span class="muted">Final unseen check.</span></div></div><div class="actions"><button id="trainBtn" disabled>Train candidate model</button><span id="trainMsg" class="muted"></span></div><div class="progress"><i id="progressBar"></i></div><p class="note">Historical optimization can overfit. Promotion is enabled only if the untouched holdout beats the baseline with positive expectancy and enough trades.</p></div>
<div id="results" class="hidden"><div class="card"><h2>3. Training verdict</h2><div id="verdict" class="banner"></div><div class="metrics" id="headlineMetrics"></div><div class="actions"><button id="promoteBtn" class="promote" disabled>Apply candidate to live DEMO thresholds</button><span id="promoteMsg" class="muted"></span></div></div><div class="card"><h2>4. Baseline vs candidate</h2><div class="splitgrid" id="splitCards"></div></div><div class="card"><h2>5. Threshold changes</h2><div class="tablewrap"><table><thead><tr><th>Parameter</th><th>Baseline</th><th>Candidate</th><th>Change</th></tr></thead><tbody id="thresholdRows"></tbody></table></div></div><div class="card"><h2>6. Finalists</h2><div class="tablewrap"><table><thead><tr><th>#</th><th>Train E</th><th>Train DD</th><th>Validation E</th><th>Validation DD</th><th>Validation trades</th></tr></thead><tbody id="finalistRows"></tbody></table></div></div></div>
</div><script>
let historyDates=[],lastCandidate=null;const $=id=>document.getElementById(id);function money(v){const n=Number(v)||0;return `${n<0?'-$':'$'}${Math.abs(n).toFixed(2)}`}function signed(v,d=2){const n=Number(v)||0;return `${n>0?'+':''}${n.toFixed(d)}`}
async function loadHistory(){try{const r=await fetch('/history/status?symbol=XAUUSD_o&timeframe=M15'),h=await r.json();if(!r.ok||!h.bars)throw new Error('No synced history yet.');historyDates=(h.available_dates||[]).slice().sort();$('historyStatus').textContent=`Synced ${h.bars} M15 bars · ${h.earliest_date} → ${h.latest_date} · ${historyDates.length} trading dates`;$('historyStatus').className='ok';for(const id of ['startDate','endDate']){$(id).min=h.earliest_date;$(id).max=h.latest_date;}$('startDate').value=historyDates[0];$('endDate').value=historyDates[historyDates.length-1];$('trainBtn').disabled=historyDates.length<15}catch(e){$('historyStatus').textContent=e.message;$('historyStatus').className='bad'}}
function metric(label,value,sub=''){return `<div class="metric"><span>${label}</span><b>${value}</b><small class="muted">${sub}</small></div>`}function splitCard(name,c,b,range){const de=c.expectancy_r-b.expectancy_r,dd=c.max_drawdown_r-b.max_drawdown_r;return `<div class="stage"><h3>${name}</h3><div class="muted">${range[0]} → ${range[1]}</div><div class="comparison"><div><small>Candidate expectancy</small><b>${c.expectancy_r.toFixed(2)}R</b></div><div><small>Baseline expectancy</small><b>${b.expectancy_r.toFixed(2)}R</b></div><div><small>Candidate avg/day</small><b>${money(c.avg_daily_pnl)}</b></div><div><small>Baseline avg/day</small><b>${money(b.avg_daily_pnl)}</b></div><div><small>Δ expectancy</small><b class="${de>=0?'ok':'bad'}">${signed(de)}R</b></div><div><small>Δ drawdown</small><b class="${dd<=0?'ok':'bad'}">${signed(dd)}R</b></div></div><p class="note">${c.trades} trades · ${c.win_rate.toFixed(1)}% WR · DD ${c.max_drawdown_r.toFixed(2)}R</p></div>`}
function render(d){lastCandidate=d.candidate.config;$('results').classList.remove('hidden');const good=d.status==='PROMISING';$('verdict').className='banner '+(good?'good':'caution');$('verdict').innerHTML=`<b>${good?'PROMISING CANDIDATE':'KEEP STABLE BASELINE'}</b><div>${d.promotion_reason}</div><div class="muted">Scenario: max ${d.max_open_trades} concurrent trades. ${d.warning}</div>`;const h=d.candidate.holdout,bh=d.baseline.holdout;$('headlineMetrics').innerHTML=metric('Holdout expectancy',`${h.expectancy_r.toFixed(2)}R/trade`,`baseline ${bh.expectancy_r.toFixed(2)}R`)+metric('Holdout avg/day',money(h.avg_daily_pnl),`target ${money(d.target_daily_pnl)}`)+metric('Holdout drawdown',`${h.max_drawdown_r.toFixed(2)}R`,`baseline ${bh.max_drawdown_r.toFixed(2)}R`)+metric('Concurrent cap',d.max_open_trades,`${d.candidates_evaluated} candidates`);$('splitCards').innerHTML=splitCard('TRAIN',d.candidate.train,d.baseline.train,d.split.train)+splitCard('VALIDATION',d.candidate.validation,d.baseline.validation,d.split.validation)+splitCard('HOLDOUT',d.candidate.holdout,d.baseline.holdout,d.split.holdout);const b=d.baseline.config,c=d.candidate.summary,labels={dynamic_levels:'Dynamic levels',static_levels:'Static / OrderBlock',fibonacci:'Fibonacci',patterns:'Patterns / Harmonic',pivots:'Pivots',divergence:'Divergence / Momentum',min_pass_count:'Minimum passed factors',min_total_score:'Minimum total score',min_side_edge:'Minimum BUY/SELL edge'};$('thresholdRows').innerHTML=Object.keys(labels).map(k=>{const x=Number(c[k])-Number(b[k]);return `<tr><td>${labels[k]}</td><td>${b[k]}</td><td>${c[k]}</td><td class="${x===0?'muted':x>0?'warn':'ok'}">${x>0?'+':''}${x}</td></tr>`}).join('');$('finalistRows').innerHTML=d.top_candidates.map((x,i)=>`<tr><td>${i+1}</td><td>${x.train.expectancy_r.toFixed(2)}R</td><td>${x.train.max_drawdown_r.toFixed(2)}R</td><td>${x.validation.expectancy_r.toFixed(2)}R</td><td>${x.validation.max_drawdown_r.toFixed(2)}R</td><td>${x.validation.trades}</td></tr>`).join('');$('promoteBtn').disabled=!d.promotion_allowed;$('promoteMsg').textContent=d.promotion_allowed?'Eligible for DEMO threshold promotion; keep the same concurrency setting for forward comparison.':'Promotion disabled because holdout gates were not passed.';$('promoteMsg').className=d.promotion_allowed?'ok':'warn'}
async function train(){const start=$('startDate').value,end=$('endDate').value,selected=historyDates.filter(x=>x>=start&&x<=end),maxOpen=Number($('maxOpen').value);if(!start||!end||start>end||selected.length<15||maxOpen<1||maxOpen>5){$('trainMsg').textContent='Check date range and max concurrent trades (1–5).';$('trainMsg').className='bad';return}const body={symbol:'XAUUSD_o',timeframe:'M15',start_date:start,end_date:end,starting_balance:Number($('balance').value),risk_percent:Number($('risk').value),reward_risk_ratio:Number($('rr').value),max_open_trades:maxOpen,iterations:Number($('iterations').value),base_profile:$('baseProfile').value,target_daily_pnl:Number($('target').value)};$('trainBtn').disabled=true;$('results').classList.add('hidden');$('trainMsg').textContent=`Training ${body.iterations} candidates across ${selected.length} days with max ${maxOpen} concurrent trades…`;$('progressBar').style.width='55%';try{const r=await fetch('/training/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Training failed');$('progressBar').style.width='100%';$('trainMsg').textContent=`Done · ${d.candidates_evaluated} candidates evaluated`;$('trainMsg').className='ok';render(d)}catch(e){$('progressBar').style.width='0';$('trainMsg').textContent=e.message;$('trainMsg').className='bad'}finally{$('trainBtn').disabled=false}}
async function promote(){if(!lastCandidate)return;const current=await(await fetch('/strategy/config')).json();lastCandidate.safety=current.safety;const r=await fetch('/strategy/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(lastCandidate)});$('promoteMsg').textContent=r.ok?'Candidate thresholds applied. Execution settings were preserved.':'Apply failed';$('promoteMsg').className=r.ok?'ok':'bad'}
$('trainBtn').addEventListener('click',train);$('promoteBtn').addEventListener('click',promote);loadHistory();
</script></body></html>'''
